heat_template_version: 2015-10-15

parameters:

  public_network_id:
    label: Public Network ID
    type: string

resources:

  network_stack: 
    type: lib/openstack/private_net.yaml
    properties: 
      public_network_id: { get_param: public_network_id }
      prefix: setup 

  security_group_icmp:
    type: lib/openstack/security_group_icmp.yaml
    properties:
      name: setup_sg_icmp

  security_group_web:
    type: lib/openstack/security_group.yaml
    properties:
      name: setup_sg_web
      ports: ['22','80','443']
      protocols: ['tcp', 'udp']

outputs: 
  instance_ip:
    description: IP address of the deployed compute instance
    value: { get_attr: [network_stack, name] }
